var data = [
  {
    name: "Rolando Garcia",
    email: "rogarcia@berkeley.edu",
    photo: "rolandoGarcia.jpg",
    website: "https://rlnsanz.github.io",
    area: "Databases",
    location: "465 Soda",
    fun_fact:
      "I enjoy practicing yoga, and listening to audiobooks on my commute from Davis",
    bio:
      "I'm now starting my 3rd year at Berkeley. It's still a little early for me to have a strong retrospective view of graduate school, but by now I've passed my prelims on the second attempt, worked at a summer internship, been a 20-hour GSI, mentored undergraduate researchers, and have worked to promote diversity in STEM by working with several organizations: many Berkeley affiliated; sometimes in a leadership capacity. I am sympathetic to sentiments that graduate school can be a little too much sometimes, and I consider myself extremely fortunate to be in the company of such bright and dedicated people. I've found that structure and exercise help me be a little more patient with myself as I learn and grow. On a more practical note, I've used (and now how to use) my medical insurance, dental insurance, and Berkeley's legal services. ",
  },
  {
    name: "Mauricio Bustamante",
    email: "mbustamante@berkeley.edu",
    photo: "mbustamante.jpg.jpeg",
    website: "",
    area: "MEMS",
    location: "468 Cory",
    fun_fact:
      "I go salsa dancing very often, and can do it well despite being pretty clumsy",
    bio:
      "I am a 3rd year student working on a MEMS microswimmer. I was born and raised in Ecuador, and adjusted to Berkeley from a small rural liberal arts school with a very small engineering program. In grad school I have dealt with finding a suitable research project, working with an advisor who is on leave, studying for prelims, and the feeling that I haven't achieved enough. I am happy to talk about personal and academic issues and the intersection between both.",
  },
  {
	name: "Elizabeth Yang", 
	email: "elizabeth_yang@berkeley.edu", 
	photo: "eyang.jpg", 
	website: "https://people.eecs.berkeley.edu/~elizabeth_yang/", 
	area: "Theory", 
	location: "Soda 643", 
	fun_fact: "In my free time, I enjoy running, crosswords, and more recently, practicing the piano.", 
	bio: "I'm currently a 4th year PhD student at Berkeley. My research interests lie primarily in spectral graph theory, more specifically approximate sampling and high-dimensional expanders. On the academic side, I'm happy to chat about picking courses, being a 20-hr GSI, being a lecturer for a summer course, and switching from my temp advisor. Outside of academic matters, I can talk about seeking mental health resources, adjusting to the Bay Area and to school after industry, and fighting impostor syndrome. Happy to listen to whatever is on your mind!"
	},
{name: "Sara Fridovich-Keil", email: "sfk@berkeley.edu", photo: "sfridovichkeil.jpg", website: "https://people.eecs.berkeley.edu/~sfk/", area: "Foundations of ML", location: "5th floor Soda Hall (FML)", fun_fact: "I have a balcony garden that produced enough tomatoes and basil I made my own marinara sauce!", bio: "I'm a 5th year PhD student focusing on 3D imaging/reconstruction. I'm also interested in ML robustness and the intersection of ML and signal processing. I'm happy to talk about finding a research advisor, choosing projects, finding housing, work-life balance, applying to fellowships and internships, handling rejection, prelims and quals, taking classes, teaching (in person or virtually)...or whatever else is on your mind!"},
{name: "Bob Zhou", email: "bob.linchuan@berkeley.edu", photo: "bobzhou.jpeg", website: "", area: "Integrated Circuits", location: "Berkeley Wireless Research Center", fun_fact: "I've bounced around various hobbies. For a while, I was deep into ballroom dance, cooking, golf, and guitar. Now I'm trying rock climbing.", bio: "I'm a 5th year PhD working on high speed wireline circuits. I grew up in Florida from a really small high school in a really small community, then came out to Berkeley. Quite the change! In grad school, I've faced part-time jobs, internship hunts, switching projects, co-advising, teaching classes (large, small, undergrad, grad), imposter syndrome, long distance relationships, isolation, mental health challenges. Grad school (and life) can be hard and has all sorts of ups and downs, and I'm happy to talk to you about anything on your mind. I believe it's important to learn about yourself and find what works well for you."},
{name: "Cathy Chen", email: "cathychen@berkeley.edu", photo: "cathychen.jpg", website: "https://cchen23.github.io/", area: "Natural Language Processing / Computational Neuroscience", location: "Berkeley, CA", fun_fact: "In my free time I enjoy running and doing crosswords", bio: "I'm a 4th year PhD student working on natural language processing and computational neuroscience. I'm happy to chat about finding a research advisor, being co-advised, adjusting to graduate school, applying to fellowships/internships, stress, and anything else that's on your mind!"},
{name: "Gabriel E. Colón-Reyes", email: "gecolonr@berkeley.edu", photo: "gabriel.jpg", website: "https://people.eecs.berkeley.edu/~gecolonr/", area: "Control and stability for power systems with renewable energy", location: "Berkeley, CA", fun_fact: "I can make latte art.", bio: "I am a Ph.D. student at UC Berkeley in the Department of Electrical Engineering and Computer Sciences. I'm very fortunate to be advised by Sascha von Meier and Claire Tomlin. I obtained my B.S. degree from the University of Puerto Rico, Mayagüez in May 2019. My research interests lie at the intersection of control and optimization theory with power systems and renewable energy incorporation in the grid. Current hobbies include sports, coffee, wine, food, dancing, and playing music."},	
{name: "Lars Tatum", email: "lpt@berkeley.edu", photo: "lars.png", website: "people.eecs.berkeley.edu/~lpt", area: "Physical electronics/semiconductor devices", location: "373 Cory Hall", fun_fact: "I once bicycled to Stanford cuz yolo", bio: "I started my PhD at Berkeley in Fall 2019, working on new fabrication processes and nanodevice designs future semiconductor nodes. I grew up and did my undergrad in Florida (go gators!) and came out to Berkeley for grad school. I'm happy to chat about whatever's on your mind! I've faced big team research projects, individual work, research successes (and failures), college football, (abroad) internships canceled, exploration of multiple research directions, passing/failing prelim, GSI'ing a lab course, imposter syndrome, health challenges, work/life balance struggles and wins, burnout, bay area explorations and adventures, music, taking non-EECS classes for fun (entrepreneurship, Chinese language). I'm a big fan of biking, music (rock, EDM, etc), and getting outdoors"},
{name: "Alok Tripathy", email: "alokt@berkeley.edu", photo: "alok.jpeg", website: "http://aloktripathy.me/", area: "Distributed & Parallel Computing", location: "5th Floor Soda Hall (SLICE Lab)", fun_fact: "I've gone to Triple Rock trivia night every week since I moved here (minus COVID-related closures), and have gotten both last place and first place :). I'm also a big fan of the New York Yankees, house music, and road trips.", bio: "I'm a CS PhD student (joined in 2019), and I'm interested in the intersection of high-performance computing, deep learning, and domain sciences (e.g. computational biology, materials science). Work-wise, I can talk about navigating co-advisorship, applying to fellowships, being in a small lab, interfacing with LBL, time management techniques, managing stress, and prioritizing rest. Outside of work, I can talk about getting involved in campus orgs (e.g. GSA, Berkeley Science Review), finding housing and friends in grad school, maintaining a long-distance relationship and long-distance friendships, going out in SF and Oakland, moving from the East Coast, feelings of inadequacy + being hard on yourself, and finding activities that energize you. Above all though, I'm more than happy to talk about anything on your mind, or be a pair of ears to listen to you if that's what you need :)."},
{name: "Orr Paradise", email: "orrp@eecs.berkeley.edu", photo: "orr_paradise.png", website: "http://people.eecs.berkeley.edu/~orrp/", area: "Theory", location: "Soda Hall", fun_fact: "Some of my research involves decoding sperm whale communication! (Shoutout Project CETI)", bio: "Hi! My name is Orr (He/him), and I’m a final-year student at the Theory group, where I research topics topics in the intersection of proof systems and machine learning. My academic experience includes switching from my temp advisor, switching research areas, (not) switching permanent co-advisors, GSI’ing a graduate-level course while learning its material, applying for fellowships, volunteering at a CS summer camp in Jamaica, and lots more. On the non-academic side, we can talk about being an international student, co-operative housing, staying healthy in grad school, hobbies, or anything else that’s on your mind. Grad school has been a fun ride with plenty of bumps along the way. I’d love to share from my experience, and hear more about yours!"},
{name: "Justin Lubin", email: "justinlubin@berkeley.edu", photo: "justin_lubin.jpg", website: "https://jlubin.net", area: "Programming languages + human-computer interaction", location: "Soda Hall, 5th floor (SLICE Lab)", fun_fact: "My partner and I have two extremely precious cats, one of which we rescued from the streets ourselves!", bio: "Hi there! I'm Justin (he/him), and I've been a CS PhD student at Berkeley since 2020. My research interests lie at the intersection of programming languages and human-computer interaction, and, lately, I've been really excited to apply techniques from these fields to build better computational tooling for biologists. My main hobby is music composition—and just engaging with music more generally, especially video game music! Regarding work topics, I'm happy to chat about topics like maintaining a healthy work-life balance, struggling to find an exciting research direction, doing interdisciplinary research (including with collaborators outside of EECS), diving into new research areas mid-PhD, mentoring undergraduate / 5th-year MS researchers, helping set up a positive research group culture, studying for the prelim exams, and feeling anxious about things like taking the prelim exam / giving oral presentations / receiving paper reviews. Outside of work topics, I'm also happy to chat about topics like maintaining a long-distance relationship, finding housing in the Bay Area, learning how to cook / meal prep, and exploring new hobbies (and maintaining old ones!) in grad school. But these topics are by no means exhaustive, and I'd really love to chat with you about whatever is on your mind! :)"},
{name: "Victoria Tuck", email: "victoria_tuck@berkeley.edu", photo: "victoria_tuck.jpg", website: "", area: "Motion Planning/Cyber-Physical Systems and Verification", location: "SDH 7", fun_fact: "I recently learned how to split an apple in half with my bare hands and am very proud of it.", bio: "I’m a PhD student focusing on motion planning for multi-agent cyber-physical systems. I’m particularly interested in decentralized systems with partial observability. Some academic things I have experience with include GSI-ing a lab course, being co-advised, taking a semester off for an internship and needing to apply for readmission into the program, withdrawing from classes, mentoring undergrads, outreach volunteering, imposter syndrome, questioning grad school, paper rejection (and acceptance!), and generally trying to find a work-life balance. I’ve found joy outside of the program singing with the campus choral program, going hiking in the area, seeing shows in SF, and drinking lots of wine in Napa. I’d be happy to talk about any of these and anything else that might be on your mind!"},
{name: "Chih-Yuan Chiu", email: "chihyuan_chiu@berkeley.edu", photo: "cyc_1.png", website: "https://chihyuanchiu.github.io/", area: "Control Theory, Dynamic Game Theory, Mechanism Design", location: "3rd floor Cory Hall (TRUST)", fun_fact: "Fun Fact: I really enjoy cooking, and I learned to cook new dishes in at least 4 kinds of cuisine (Indian, Ethiopian, Italian, Chinese) over the course of the last few months, and look forward to learning more in the near future.", bio: "I’m a 6th year PhD student applying tools from game theory and mechanism design to improve safety and efficiency in modern transportation systems. I’m happy to talk about anything academic or non-academic, up to and including finding housing, selecting projects, searching for a permanent advisor, resolving administrative issues, managing work-life balance, practicing for and taking prelims and quals, taking classes, teaching (in person or on Zoom)."},
{name: "Hellina Hailu Nigatu", email: "hellina_nigatu@berkeley.edu", photo: "hellina_nigatu.jpeg", website: "https://hhnigatu.github.io", area: "Natural Language Processing (NLP) + human-computer interaction (HCI) + Ethical AI", location: "Soda Hall, 5th floor (SLICE Lab)", fun_fact: "I make my own Injera :-)))))", bio: "Hello! My name is Hellina (she/her), and I am a 3rd year PhD student in the EECS department. My research is in the intersection of NLP, HCI and ethics; I am particularity interested in building language technologies for low-resourced language (languages that do not have a lot of available data) speakers and understanding the impact of current AI systems as it relates to low-resourced language speakers. In my free time, I mostly talk with my family, read books, or make Ethiopian coffee. I am also really interested in languages: I am learning Arabic this year . I have also started learning how to play a musical instrument called Masinqo. I am on the EB for the Black Graduate Engineering and Science Students (BGESS) organisation and I focus on increasing access to research opportunities to Black undergrads at Berkeley and beyond. I am happy to chat about research related stuff, pivoting during your PhD, BGESS stuff, international student life and dealing with homesickness  , languages, finding and being a mentor, prelims, culture (and culture shock!!), and anything else related to my experience as a grad student."},
{name: "Serena Caraco", email: "caraco@berkeley.edu", photo: "serena_caraco.jpg", website: "", area: "Software Engineering Education, Instructor Support Tools", location: "ACE Lab (w/ a hint of PLAIT)", fun_fact: "The profile picture was taken in the historic Berkeley City Club! They offer pay-as-you-can community theater, different workshops and classes, and have a few small, public art exhibits (in addition to the legendary architecture)!", bio: "I'm a fourth year PhD student at Berkeley - I love all things education, programming languages, and games. In terms of experience: I GSl'ed a (delightfully) nightmarish summer course, I took the HCl prelim (after a long torturous decision process), and I publicly transitioned (definitely still on going). I'm involved in the union and a couple affinity groups on campus. I love to chat, and am very open to emails or slacks (though please include \"popcorn\" in your intro so I know where you're coming from!). I'm still figuring out \"how to PhD,\" but with any luck my quals will be underway soon!"},
{name: "Peter Wu", email: "peterw1@berkeley.edu", photo: "peter_wu.jpg", website: "https://peter.onrender.com/", area: "Machine Learning, Low-resource speech NLP", location: "Berkeley", fun_fact: "I work with hundreds of languages in my research, with the goal of having NLP systems perform well in all of them.", bio: "Peter is a PhD student researching machine learning and low-resource speech NLP."}
	];
